02.05.2025 14-26-27 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 4: 'cache'. Did you forget to register or load this tag?"), <traceback object at 0x000002C2CDA87140>)
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'cache'. Did you forget to register or load this tag?
02.05.2025 14-26-35 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 172839 None
03.05.2025 20-50-24 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'AttributeError'>, AttributeError("'News' object has no attribute 'method'"), <traceback object at 0x00000216DBAEC580>)
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 181, in _view_wrapper
    result = _pre_process_request(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 127, in _pre_process_request
    result = middleware.process_request(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\middleware\cache.py", line 156, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'News' object has no attribute 'method'
03.05.2025 20-50-25 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 103565 None
03.05.2025 23-36-27 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'AttributeError'>, AttributeError("'News' object has no attribute 'method'"), <traceback object at 0x0000019DF10EDB00>)
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 181, in _view_wrapper
    result = _pre_process_request(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 127, in _pre_process_request
    result = middleware.process_request(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\middleware\cache.py", line 156, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'News' object has no attribute 'method'
03.05.2025 23-36-29 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 103565 None
04.05.2025 19-14-53 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'AttributeError'>, AttributeError("'News' object has no attribute 'method'"), <traceback object at 0x000002055250C4C0>)
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 181, in _view_wrapper
    result = _pre_process_request(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 127, in _pre_process_request
    result = middleware.process_request(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\middleware\cache.py", line 156, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'News' object has no attribute 'method'
04.05.2025 19-14-54 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 104157 None
04.05.2025 19-31-02 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'AttributeError'>, AttributeError("'News' object has no attribute 'method'"), <traceback object at 0x000001C8F9902E00>)
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 181, in _view_wrapper
    result = _pre_process_request(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 127, in _pre_process_request
    result = middleware.process_request(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\middleware\cache.py", line 156, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'News' object has no attribute 'method'
04.05.2025 19-31-03 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 104157 None
04.05.2025 19-40-56 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'AttributeError'>, AttributeError("'News' object has no attribute 'method'"), <traceback object at 0x000001FA3F706D00>)
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 181, in _view_wrapper
    result = _pre_process_request(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\decorators.py", line 127, in _pre_process_request
    result = middleware.process_request(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\middleware\cache.py", line 156, in process_request
    if request.method not in ("GET", "HEAD"):
       ^^^^^^^^^^^^^^
AttributeError: 'News' object has no attribute 'method'
04.05.2025 19-40-58 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 104029 None
04.05.2025 20-00-39 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'profile' not found. 'profile' is not a valid view function or pattern name."), <traceback object at 0x000001A263FD7D80>)
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' not found. 'profile' is not a valid view function or pattern name.
04.05.2025 20-00-40 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 148691 None
04.05.2025 21-07-14 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'post_create' not found. 'post_create' is not a valid view function or pattern name."), <traceback object at 0x000001D1819BAAC0>)
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_create' not found. 'post_create' is not a valid view function or pattern name.
04.05.2025 21-07-15 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 136095 None
04.05.2025 21-11-11 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.title_en_us'), <traceback object at 0x000002A388041B40>)
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: news_post.title_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1067, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 745, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\defaultfilters.py", line 632, in length
    return len(value)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: news_post.title_en_us
04.05.2025 21-11-13 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 210165 None
04.05.2025 21-14-39 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'username'"), <traceback object at 0x000002A387E009C0>)
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1067, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 917, in _resolve_lookup
    current = current()
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\utils.py", line 87, in as_p
    return self.render(self.template_name_p)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\utils.py", line 55, in render
    return mark_safe(renderer.render(template, context))
                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\renderers.py", line 29, in render
    return template.render(context, request=request).strip()
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1073, in render
    return render_value_in_context(output, context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1050, in render_value_in_context
    value = str(value)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\utils.py", line 79, in __str__
    return self.as_widget()
           ~~~~~~~~~~~~~~^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\boundfield.py", line 108, in as_widget
    return widget.render(
           ~~~~~~~~~~~~~^
        name=self.html_initial_name if only_initial else self.html_name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        renderer=self.form.renderer,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\widgets.py", line 764, in get_context
    context = super().get_context(name, value, attrs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\widgets.py", line 715, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ~~~~~~~~~~~~~~^
        name, context["widget"]["value"], attrs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\widgets.py", line 655, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
                                               ~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django_filters\fields.py", line 256, in __iter__
    yield from iterable
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\models.py", line 1425, in __iter__
    yield self.choice(obj)
          ~~~~~~~~~~~^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\models.py", line 1439, in choice
    self.field.label_from_instance(obj),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\models.py", line 1529, in label_from_instance
    return str(obj)
  File "C:\Users\Семья\PycharmProjects\project_dir\project\news\models.py", line 25, in __str__
    return self.user.username
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'username'
04.05.2025 21-14-40 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 289527 None
04.05.2025 22-33-57 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'username'"), <traceback object at 0x0000021408D50400>)
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1067, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 917, in _resolve_lookup
    current = current()
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\utils.py", line 87, in as_p
    return self.render(self.template_name_p)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\utils.py", line 55, in render
    return mark_safe(renderer.render(template, context))
                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\renderers.py", line 29, in render
    return template.render(context, request=request).strip()
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1073, in render
    return render_value_in_context(output, context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1050, in render_value_in_context
    value = str(value)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\utils.py", line 79, in __str__
    return self.as_widget()
           ~~~~~~~~~~~~~~^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\boundfield.py", line 108, in as_widget
    return widget.render(
           ~~~~~~~~~~~~~^
        name=self.html_initial_name if only_initial else self.html_name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        renderer=self.form.renderer,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\widgets.py", line 764, in get_context
    context = super().get_context(name, value, attrs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\widgets.py", line 715, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ~~~~~~~~~~~~~~^
        name, context["widget"]["value"], attrs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\widgets.py", line 655, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
                                               ~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django_filters\fields.py", line 256, in __iter__
    yield from iterable
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\models.py", line 1425, in __iter__
    yield self.choice(obj)
          ~~~~~~~~~~~^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\models.py", line 1439, in choice
    self.field.label_from_instance(obj),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\forms\models.py", line 1529, in label_from_instance
    return str(obj)
  File "C:\Users\Семья\PycharmProjects\project_dir\project\news\models.py", line 25, in __str__
    return self.user.username
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'username'
04.05.2025 22-33-59 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/?title__icontains=&author=&date_in= HTTP/1.1" 500 290591 None
04.05.2025 23-07-27 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /profile/ (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('default.html'), <traceback object at 0x0000025FBFE98500>)
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: default.html
04.05.2025 23-07-29 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /profile/ HTTP/1.1" 500 129215 None
05.05.2025 22-20-33 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/time_zone/ (<class 'django.utils.datastructures.MultiValueDictKeyError'>, MultiValueDictKeyError('timezone'), <traceback object at 0x000001D4C0F47B00>)
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'timezone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Семья\PycharmProjects\project_dir\project\news\views.py", line 176, in post
    request.session['django_timezone'] = request.POST['timezone']
                                         ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'timezone'
05.05.2025 22-20-34 ERROR C:\Users\Семья\PycharmProjects\project_dir\.venv\Lib\site-packages\django\core\servers\basehttp.py "POST /news/time_zone/ HTTP/1.1" 500 87576 None
